# Generated by Django 4.2.23 on 2025-07-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(db_index=True, max_length=3000, verbose_name='Описание товара')),
                ('image_url', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара')),
                ('condition', models.CharField(choices=[('Новый', 'Новый'), ('б/у', 'б/у')], db_index=True, max_length=50, verbose_name='Состояние товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявление',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_index=True, max_length=3000, verbose_name='Описание товара')),
                ('status', models.CharField(choices=[('ожидает', 'ожидает'), ('принята', 'принята'), ('отклонена', 'отклонена')], db_index=True, max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', related_query_name='ad', to=settings.AUTH_USER_MODEL),
        ),
    ]
