# Generated by Django 4.2.23 on 2025-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.TextField(db_index=True, max_length=3000, verbose_name='Комментарий'),
        ),
    ]
