# Generated by Django 4.2.23 on 2025-07-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_exchangeproposal_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложение обмена'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('принята', 'принята'), ('отклонена', 'отклонена')], db_index=True, default='ожидает', max_length=50, verbose_name='Статус'),
        ),
    ]
